config/routes.rb
Rails.application.routes.draw do

  resources :nested_invoices

  resources :invoices
  resources :line_items do
    put :save_all, on: :collection
  end

  resources :boxes, only: [:create, :update, :index]
  resources :box_line_items, only: [:destroy] do
    put :save_all, on: :collection
  end

  root to: "invoices#index"

end

app/controllers/nested_invoices_controller.rb
class NestedInvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # TODO abstract to kindred
  after_action :setup_kindred

  helper_method :js

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  def edit
    @invoice = Invoice.find(params[:id])
    @boxes = @invoice.boxes
    @box_line_items = BoxLineItem.where(box_id: @boxes.map(&:id))
    js
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:date, :subtotal_cents, :shipping_cents, :tax_cents, :total_cents, :amount_due)
    end

    # TODO move this
    def setup_kindred
      view_context.content_for :kindred_script do
        js(js_class: "App.Template", function: "set_templates", args: @kindred_hash, rendered: true)
      end
    end

end

app/views/nested_invoices/_form.html.erb
<%= form_for(@invoice) do |f| %>
  <% if @invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% @invoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit class: "button-blue" %>
  </div>
<% end %>

app/views/nested_invoices/edit.html.erb
<h3>Boxes</h3>
<fieldset id="boxes">
  <div <%= target @invoice %>>
    <div class="row">
      <div class="large-12 columns">
        <%= link_to '+ New Box', "#", class: "new-box button tiny right",
            data: { target_uuid: @invoice.uuid, "invoice_id" => @invoice.id } %>
        <%= link_to 'Save All', "#", id: "box-line-items-save-all", class: "button tiny right" %>
      </div>
    </div>
    <%= template(collection: @boxes, target_uuid: @invoice.uuid, model: "box") do %>
      <%= k_hidden_field_tag :delete_box %>
      <%= k_hidden_field_tag :invoice_id, @invoice.id %>
      <fieldset data-k-uuid="{{box.uuid}}">

        <legend>Box #{{box.id}}</legend>
        <table style="width: 100%" border="1">
          <thead>
            <tr>
              <th>QTY</th>
              <th>Color</th>
              <th>Desc</th>
              <th></th>
            </tr>
          </thead>
          <!-- TODO Need data helper here -->
          <tbody data-target-uuid="{{box.uuid}}", data-target>
            <%= link_to fa_icon("fa-minus-circle", text: "Delete",
              class: "fa-minus-circle"), "#", class: "delete-box box-level right",
              data: { k_uuid: "{{box_line_item.uuid}}" } %>
            <%= link_to fa_icon("fa-plus-circle", text: "Add Back",
              class: "fa-plus-circle"), "#", class: "add-box-back box-level hide right",
              data: { k_uuid: "{{box_line_item.uuid}}" } %>
            <%= link_to 'New Box Line Item', "#", class: "new-box-line-item button tiny",
              data: { box_id: "{{box.id}}", "target_uuid" => "{{box.uuid}}" } %>
            <%= template(collection: @box_line_items, target_uuid: "box", model: "box_line_item") do %>
              <tr>
                <td>
                  <%= k_text_field_tag(:box_line_item, :qty) %>
                  <%= error_for(:box_line_item, :qty) %>
                </td>
                <td>
                  <%= k_text_field_tag(:box_line_item, :color, disabled: true) %>
                  <%= error_for(:box_line_item, :color) %>
                </td>
                <td>
                  <%= k_text_field_tag(:box_line_item, :description, disabled: true) %>
                  <%= error_for(:box_line_item, :description) %>
                </td>
                <td>
                  <%= k_hidden_field_tag :box_id %>
                  <%= k_hidden_field_tag :delete %>
                  <%= link_to fa_icon("fa-minus-circle", text: "Remove",
                        class: "fa-minus-circle"), "#", class: "remove-box-li",
                        data: { k_uuid: "{{box_line_item.uuid}}" } %>
                  <%= link_to fa_icon("fa-plus-circle", text: "Add Back",
                        class: "fa-plus-circle"), "#", class: "add-box-li-back hide",
                        data: { k_uuid: "{{box_line_item.uuid}}" } %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </fieldset>
    <% end %>
  </div>
</fieldset>

app/views/nested_invoices/index.html.erb
<h1>Listing invoices</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Subtotal cents</th>
      <th>Shipping cents</th>
      <th>Tax cents</th>
      <th>Total cents</th>
      <th>Amount due</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.date %></td>
        <td><%= invoice.subtotal_cents %></td>
        <td><%= invoice.shipping_cents %></td>
        <td><%= invoice.tax_cents %></td>
        <td><%= invoice.total_cents %></td>
        <td><%= invoice.amount_due %></td>
        <td><%= link_to 'Show', invoice %></td>
        <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
        <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invoice', new_invoice_path %>

app/views/nested_invoices/new.html.erb
<h1>New invoice</h1>

<%= render 'form' %>

<%= link_to 'Back', invoices_path %>

app/views/nested_invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @invoice.date %>
</p>

<p>
  <strong>Subtotal cents:</strong>
  <%= @invoice.subtotal_cents %>
</p>

<p>
  <strong>Shipping cents:</strong>
  <%= @invoice.shipping_cents %>
</p>

<p>
  <strong>Tax cents:</strong>
  <%= @invoice.tax_cents %>
</p>

<p>
  <strong>Total cents:</strong>
  <%= @invoice.total_cents %>
</p>

<p>
  <strong>Amount due:</strong>
  <%= @invoice.amount_due %>
</p>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>